/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUICreacionJuego;


import quiz2.Quiz2;
import java.awt.Dimension;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lucho
 */
public class Ventana1 extends javax.swing.JFrame implements Runnable{
    int hx=0,hy=0;
    
    int tamx,tamy;
    ArrayList<Integer> Objetivosx;
    ArrayList<Integer> Objetivosy;
    ArrayList<Integer> Obstaculox;
    ArrayList<Integer> Obstaculoy;
    ArrayList<Integer> enemigox;
    ArrayList<Integer> enemigoy;

    /**
     * Creates new form NewJFrame
     */
    public Ventana1() {
        initComponents();
        Objetivosx = new ArrayList<>();
        Objetivosy = new ArrayList<>();
        Obstaculox = new ArrayList<>();
        Obstaculoy = new ArrayList<>();
        enemigox = new ArrayList<>();
        enemigoy = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heroe = new javax.swing.JButton();
        Obstaculo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        escribirautor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        escribirdescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Objetivo = new javax.swing.JButton();
        Enemigo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        Heroe.setText("Heroe");
        Heroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeroeActionPerformed(evt);
            }
        });
        getContentPane().add(Heroe);
        Heroe.setBounds(20, 260, 90, 25);

        Obstaculo.setText("+ Obstaculo");
        Obstaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObstaculoActionPerformed(evt);
            }
        });
        getContentPane().add(Obstaculo);
        Obstaculo.setBounds(391, 260, 120, 25);

        jLabel2.setText("Autor: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 40, 16);

        escribirautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escribirautorActionPerformed(evt);
            }
        });
        getContentPane().add(escribirautor);
        escribirautor.setBounds(130, 90, 553, 22);

        jLabel3.setText("Descipción: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 69, 16);

        escribirdescripcion.setColumns(20);
        escribirdescripcion.setRows(5);
        jScrollPane1.setViewportView(escribirdescripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 150, 553, 51);

        jLabel4.setText("Empiza a crear tu juego");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 220, 137, 16);

        Objetivo.setText("+ Objetivo");
        Objetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetivoActionPerformed(evt);
            }
        });
        getContentPane().add(Objetivo);
        Objetivo.setBounds(561, 260, 120, 25);

        Enemigo.setText("+ Enemigo");
        Enemigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnemigoActionPerformed(evt);
            }
        });
        getContentPane().add(Enemigo);
        Enemigo.setBounds(183, 260, 110, 25);

        jButton5.setText("crear juego");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(510, 320, 210, 25);

        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(277, 320, 140, 25);

        jButton2.setText("objetivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(57, 320, 110, 25);

        jLabel1.setText("autor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 30, 16);

        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });
        getContentPane().add(autor);
        autor.setBounds(130, 40, 550, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int m=0;
int n=1;
int o=1;
int p=1;

    private void escribirautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escribirautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escribirautorActionPerformed

    private void HeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeroeActionPerformed
        //Hero}
        
        
       if(m==0){
        String HX = JOptionPane.showInputDialog(null, "posicion del heroe en x");
        String HY = JOptionPane.showInputDialog(null, "posicion del heroe en y");
        hx=Integer.parseInt(HX);
        hy=Integer.parseInt(HY);
       
           System.out.println(hx+"  "+hy);
        
        
        }else{JOptionPane.showMessageDialog(null,"NO SE PUEDE TENER MAS DE UN HEROE"); }
       
       m++;
        
    }//GEN-LAST:event_HeroeActionPerformed

  
    public void setTamx(int tamx) {
        this.tamx = tamx;
    }

    public void setTamy(int tamy) {
        this.tamy = tamy;
    }

    private void ObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetivoActionPerformed
     //+Objetivo
        String OBJX = JOptionPane.showInputDialog(null, "posicion del objetivo "+n+" en x");
        String OBJY = JOptionPane.showInputDialog(null, "posicion del objetivo "+n+" en y");
        
        Objetivosx.add(Integer.parseInt(OBJX));
        Objetivosy.add(Integer.parseInt(OBJY));
        for (int i = 0; i < n ; i++) {
            System.out.print(Objetivosx.get(i) + " ");
            System.out.print(Objetivosy.get(i));
        }
        
        n++;
        
    }//GEN-LAST:event_ObjetivoActionPerformed

    private void ObstaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObstaculoActionPerformed
        //+Obstaculo
        String OBSX = JOptionPane.showInputDialog(null, "posicion del objetivo "+o+" en x");
        String OBSY = JOptionPane.showInputDialog(null, "posicion del objetivo "+o+" en y");
       
        Obstaculox.add(Integer.parseInt(OBSX));
        Obstaculoy.add(Integer.parseInt(OBSY));
        
        o++;
        
    }//GEN-LAST:event_ObstaculoActionPerformed

    private void EnemigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnemigoActionPerformed
        //+Enemigo
        String ENEX = JOptionPane.showInputDialog(null, "posicion del objetivo "+p+" en x");
        String ENEY = JOptionPane.showInputDialog(null, "posicion del objetivo "+p+" en y");
        
        enemigox.add(Integer.parseInt(ENEX));
        enemigoy.add(Integer.parseInt(ENEY));
        
        p++; 
        
    }//GEN-LAST:event_EnemigoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Guardar
        System.out.println(hx);
        
        
        JFrame frame = new JFrame();
        frame.setTitle("juego");
        
        frame.setSize(new Dimension(((tamx+2)*60)-3*tamx,(((2+tamy)*60))-tamy));
        frame.add(new Quiz2(tamx,tamy));//adicionando el panel
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
      
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enemigo;
    private javax.swing.JButton Heroe;
    private javax.swing.JButton Objetivo;
    private javax.swing.JButton Obstaculo;
    private javax.swing.JTextField autor;
    private javax.swing.JTextField escribirautor;
    private javax.swing.JTextArea escribirdescripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
         new Ventana1().setVisible(true);
    }
}
