/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUICreacionJuego;


import quiz2.Quiz2;
import java.awt.Dimension;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lucho
 */
public class Ventana1 extends javax.swing.JFrame {
    
    int tamx,tamy;
    ArrayList<Integer> Objetivosx;
    ArrayList<Integer> Objetivosy;
    ArrayList<Integer> Obstaculox;
    ArrayList<Integer> Obstaculoy;
    ArrayList<Integer> enemigox;
    ArrayList<Integer> enemigoy;

    /**
     * Creates new form NewJFrame
     */
    public Ventana1() {
        initComponents();
        Objetivosx = new ArrayList<>();
        Objetivosy = new ArrayList<>();
        Obstaculox = new ArrayList<>();
        Obstaculoy = new ArrayList<>();
        enemigox = new ArrayList<>();
        enemigoy = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heroe = new javax.swing.JButton();
        Obstaculo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Objetivo = new javax.swing.JButton();
        Enemigo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        Heroe.setText("Heroe");
        Heroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeroeActionPerformed(evt);
            }
        });
        getContentPane().add(Heroe);
        Heroe.setBounds(20, 260, 67, 25);

        Obstaculo.setText("+ Obstaculo");
        Obstaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObstaculoActionPerformed(evt);
            }
        });
        getContentPane().add(Obstaculo);
        Obstaculo.setBounds(410, 260, 101, 25);

        jLabel2.setText("Autor: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 40, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 90, 553, 22);

        jLabel3.setText("Descipción: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 69, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 150, 553, 51);

        jLabel4.setText("Empiza a crear tu juego");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 220, 137, 16);

        Objetivo.setText("+ Objetivo");
        Objetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetivoActionPerformed(evt);
            }
        });
        getContentPane().add(Objetivo);
        Objetivo.setBounds(590, 260, 91, 25);

        Enemigo.setText("+ Enemigo");
        Enemigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnemigoActionPerformed(evt);
            }
        });
        getContentPane().add(Enemigo);
        Enemigo.setBounds(200, 260, 93, 25);

        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 310, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int m=0;
int n=1;
int o=1;
int p=1;
int hx,hy;
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void HeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeroeActionPerformed
        //Hero}
        
        
       if(m==0){
        String HX = JOptionPane.showInputDialog(null, "posicion del heroe en x");
        String HY = JOptionPane.showInputDialog(null, "posicion del heroe en y");
        
        hx=Integer.parseInt(HX);
        hy=Integer.parseInt(HY);
        
        
        
        
        }else{JOptionPane.showMessageDialog(null,"NO SE PUEDE TENER MAS DE UN HEROE"); }
       
       m++;
        
    }//GEN-LAST:event_HeroeActionPerformed

    public int getHx() {
        return hx;
    }
    int mo=getHx();

    public int getMo() {
        return mo;
    }

    public void setHx(int hx) {
        this.hx = hx;
    }

    public int getHy() {
        return hy;
    }

    public void setHy(int hy) {
        this.hy = hy;
    }

    public void setTamx(int tamx) {
        this.tamx = tamx;
    }

    public void setTamy(int tamy) {
        this.tamy = tamy;
    }

    private void ObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetivoActionPerformed
     //+Objetivo
        String OBJX = JOptionPane.showInputDialog(null, "posicion del objetivo "+n+" en x");
        String OBJY = JOptionPane.showInputDialog(null, "posicion del objetivo "+n+" en y");
        
        Objetivosx.add(Integer.parseInt(OBJX));
        Objetivosy.add(Integer.parseInt(OBJY));
        for (int i = 0; i < n ; i++) {
            System.out.print(Objetivosx.get(i) + " ");
            System.out.print(Objetivosy.get(i));
        }
        
        n++;
        
    }//GEN-LAST:event_ObjetivoActionPerformed

    private void ObstaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObstaculoActionPerformed
        //+Obstaculo
        String OBSX = JOptionPane.showInputDialog(null, "posicion del objetivo "+o+" en x");
        String OBSY = JOptionPane.showInputDialog(null, "posicion del objetivo "+o+" en y");
       
        Obstaculox.add(Integer.parseInt(OBSX));
        Obstaculoy.add(Integer.parseInt(OBSY));
        
        o++;
        
    }//GEN-LAST:event_ObstaculoActionPerformed

    private void EnemigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnemigoActionPerformed
        //+Enemigo
        String ENEX = JOptionPane.showInputDialog(null, "posicion del objetivo "+p+" en x");
        String ENEY = JOptionPane.showInputDialog(null, "posicion del objetivo "+p+" en y");
        
        enemigox.add(Integer.parseInt(ENEX));
        enemigoy.add(Integer.parseInt(ENEY));
        
        p++; 
        
    }//GEN-LAST:event_EnemigoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Guardar
        JFrame frame = new JFrame();
        frame.setTitle("juego");
        int mm=500;
        frame.setSize(new Dimension(tamx*60,tamy*60));
        frame.add(new Quiz2());//adicionando el panel
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        
      
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enemigo;
    private javax.swing.JButton Heroe;
    private javax.swing.JButton Objetivo;
    private javax.swing.JButton Obstaculo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
