/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUICreacionJuego;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author lucho
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Heroe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(22, 164, 67, 25);

        jButton2.setText("+ Obstaculo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 164, 101, 25);

        jLabel1.setText("Nombre del Jueg: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 16, 105, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(135, 13, 553, 22);

        jLabel2.setText("Autor: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 45, 40, 16);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(135, 42, 553, 22);

        jLabel3.setText("Descipción: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 71, 69, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(135, 71, 553, 51);

        jLabel4.setText("Empiza a crear tu juego");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 135, 137, 16);

        jButton3.setText("+ Objetivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(597, 164, 91, 25);

        jButton4.setText("+ Enemigo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(215, 164, 93, 25);

        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(315, 217, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int m=0;
int n=1;
int o=1;
int p=1;

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Hero}
        
        
       if(m==0){
        String HX = JOptionPane.showInputDialog(null, "posicion del heroe en x");
        String HY = JOptionPane.showInputDialog(null, "posicion del heroe en y");
        int hx,hy;
        hx=Integer.parseInt(HX);
        hy=Integer.parseInt(HY);
        
        
        try{
            FileInputStream fstream = new FileInputStream("url");
            DataInputStream entrada = new DataInputStream(fstream);
            BufferedReader buffer = new BufferedReader(new InputStreamReader(entrada));
            String strLinea;
            
            while ((strLinea = buffer.readLine()) != null)   {
            
            File f;
            f = new File(strLinea,"hero");
            try{FileWriter w = new FileWriter(f);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);  
            wr.write(hx+" "+hy);
            wr.close();
            bw.close();
            }catch(IOException e){};
           
            File fhero = new File("urlhero");
try{
FileWriter w = new FileWriter(fhero);
BufferedWriter bw = new BufferedWriter(w);
PrintWriter wr = new PrintWriter(bw);  
wr.write(f.getAbsolutePath());

wr.close();
bw.close();
}catch(IOException e){};
            }
            entrada.close();
        }catch (Exception e){ 
            System.err.println("Ocurrio un error: " + e.getMessage());
        }
        
        }else{JOptionPane.showMessageDialog(null,"NO SE PUEDE TENER MAS DE UN HEROE"); }
       
       m++;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     //+Objetivo
        String OBJX = JOptionPane.showInputDialog(null, "posicion del objetivo "+n+" en x");
        String OBJY = JOptionPane.showInputDialog(null, "posicion del objetivo "+n+" en y");
        int ojx,ojy;
        ojx=Integer.parseInt(OBJX);
        ojy=Integer.parseInt(OBJY);
        
        try{
            FileInputStream fstream = new FileInputStream("url");
            DataInputStream entrada = new DataInputStream(fstream);
            BufferedReader buffer = new BufferedReader(new InputStreamReader(entrada));
            String strLinea;
            
            while ((strLinea = buffer.readLine()) != null)   {
            
            File f;
            f = new File(strLinea,"objetivos");
            try{FileWriter w = new FileWriter(f, true);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);  
            wr.write(n+" "+ojx+" "+ojy+"\n");
            wr.close();
            bw.close();
            }catch(IOException e){};
            
            File fobj = new File("urlobjeto");
try{
FileWriter w = new FileWriter(fobj);
BufferedWriter bw = new BufferedWriter(w);
PrintWriter wr = new PrintWriter(bw);  
wr.write(f.getAbsolutePath());

wr.close();
bw.close();
}catch(IOException e){};
            }
            entrada.close();
        }catch (Exception e){ 
            System.err.println("Ocurrio un error: " + e.getMessage());
        }
        n++;
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //+Obstaculo
        String OBSX = JOptionPane.showInputDialog(null, "posicion del objetivo "+o+" en x");
        String OBSY = JOptionPane.showInputDialog(null, "posicion del objetivo "+o+" en y");
       
        int obsx,obsy;
        obsx=Integer.parseInt(OBSX);
        obsy=Integer.parseInt(OBSY);
        if(o==1){
        try{
            FileInputStream fstream = new FileInputStream("url");
            DataInputStream entrada = new DataInputStream(fstream);
            BufferedReader buffer = new BufferedReader(new InputStreamReader(entrada));
            String strLinea;
            
            while ((strLinea = buffer.readLine()) != null)   {
            
            File f;
            f = new File(strLinea,"obstaculos");
            try{FileWriter w = new FileWriter(f, true);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);  
            wr.write(o+" "+obsx+" "+obsy+"\n");
            wr.close();
            bw.close();
            }catch(IOException e){};
            File fo = new File("urlobstaculo");
try{
FileWriter w = new FileWriter(fo);
BufferedWriter bw = new BufferedWriter(w);
PrintWriter wr = new PrintWriter(bw);  
wr.write(f.getAbsolutePath());

wr.close();
bw.close();
}catch(IOException e){};
            }
            entrada.close();
        }catch (Exception e){ 
            System.err.println("Ocurrio un error: " + e.getMessage());
        }}else{
            
        }
        o++;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //+Enemigo
        String ENEX = JOptionPane.showInputDialog(null, "posicion del objetivo "+p+" en x");
        String ENEY = JOptionPane.showInputDialog(null, "posicion del objetivo "+p+" en y");
        int enex,eney;
        enex=Integer.parseInt(ENEX);
        eney=Integer.parseInt(ENEY);
        if(n==1){
        try{
            FileInputStream fstream = new FileInputStream("url");
            DataInputStream entrada = new DataInputStream(fstream);
            BufferedReader buffer = new BufferedReader(new InputStreamReader(entrada));
            String strLinea;
            
            while ((strLinea = buffer.readLine()) != null)   {
            
            File fenemigos;
            fenemigos = new File(strLinea,"enemigos");
            try{FileWriter w = new FileWriter(fenemigos, true);
            BufferedWriter bw = new BufferedWriter(w);
            PrintWriter wr = new PrintWriter(bw);  
            wr.write(p+" "+enex+" "+eney+"\n");
            wr.close();
            bw.close();
            }catch(IOException e){};
            File fe = new File("urlenemigo");
try{
FileWriter w = new FileWriter(fe);
BufferedWriter bw = new BufferedWriter(w);
PrintWriter wr = new PrintWriter(bw);  
wr.write(fenemigos.getAbsolutePath());

wr.close();
bw.close();
}catch(IOException e){};
            }
            entrada.close();
        }catch (Exception e){ 
            System.err.println("Ocurrio un error: " + e.getMessage());
        }}else{
            
        }
        p++; 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Guardar
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
